import type { TermsData } from '../types'

// Loaded at runtime from /terms.json (generated by scripts/build-manifest.ts)
let cache: TermsData | null = null

export async function fetchTerms(): Promise<TermsData> {
  if (cache) return cache
  const res = await fetch('/terms.json')
  if (!res.ok) throw new Error(`Failed to load terms: ${res.status}`)
  cache = await res.json()
  return cache!
}
